import type { ComponentType } from "react";
import {
  Phone, Download, Award, FileText, CheckCircle,
  GraduationCap, School, Library, Trophy, Medal, Crown, Star, Sparkles,
  Calendar, Clock, Users, UserCheck, UserPlus,
  Calculator, FlaskConical, Microscope, Atom, Brain, Lightbulb, Puzzle, Target,
  BarChart3, TrendingUp, Activity, PieChart,
  Bell, Megaphone, Gift, PartyPopper,
  Video, Camera, Music,
  Wallet, CreditCard, DollarSign, Tag, Ticket,
  Zap, Rocket, Compass, Search,
  Heart, Coffee, Home, Sun, Moon,
  Mail, MessageCircle, MapPin, Globe,
  ClipboardList, ClipboardCheck, NotebookPen, BookOpen, BookMarked, PenTool,
} from "lucide-react";

// Icon map terpusat — dipakai bersama oleh admin icon picker & frontend render
// (QuickActionCards). Tambahkan icon baru di sini agar tersedia di kedua sisi.
export const LUCIDE_ICON_MAP: Record<string, ComponentType<{ className?: string }>> = {
  Phone,
  Download,
  Award,
  FileText,
  CheckCircle,
  GraduationCap,
  School,
  Library,
  Trophy,
  Medal,
  Crown,
  Star,
  Sparkles,
  Calendar,
  Clock,
  Users,
  UserCheck,
  UserPlus,
  Calculator,
  FlaskConical,
  Microscope,
  Atom,
  Brain,
  Lightbulb,
  Puzzle,
  Target,
  BarChart3,
  TrendingUp,
  Activity,
  PieChart,
  Bell,
  Megaphone,
  Gift,
  PartyPopper,
  Video,
  Camera,
  Music,
  Wallet,
  CreditCard,
  DollarSign,
  Tag,
  Ticket,
  Zap,
  Rocket,
  Compass,
  Search,
  Heart,
  Coffee,
  Home,
  Sun,
  Moon,
  Mail,
  MessageCircle,
  MapPin,
  Globe,
  ClipboardList,
  ClipboardCheck,
  NotebookPen,
  BookOpen,
  BookMarked,
  PenTool,
};

export const LUCIDE_ICON_OPTIONS = Object.keys(LUCIDE_ICON_MAP).sort();

export function getLucideIcon(name: string | null | undefined): ComponentType<{ className?: string }> {
  if (!name) return CheckCircle;
  return LUCIDE_ICON_MAP[name] ?? CheckCircle;
}
